### ISSUE TITLE
Bookmarklet to save to bookmarks.dev

### ISSUE THREAD

**Issue by nfultz** [CodepediaOrg/bookmarks.dev#25]
Thank you for building this site - it's like a well curated pinboard for professional topics. It would be really nice to have a bookmarklet to save sites (a short javascript snippet that can live in the bookmarks bar), so that I don't have to manually copy-paste URLS from my location bar to the web form.

You can see how pinboard does it here: https://pinboard.in/howto/

**Comment by adrianmatei-me** [comment]
hey @nfultz thanks and thanks for the suggestion, it would definitely make bookmarking easier - will look more into it.

**Comment by adrianmatei-me** [comment]
A "Bookmarklet" link has been added to the navigation menu. When clicked the current location is automatically completed in the Add New Bookmark form and some fields (e.g. title, description or tags) are autocompleted. Once  saved the user is redirected back to the original location.

**Comment by nfultz** [comment]
Thanks, I will give it a try.

**Comment by adrianmatei-me** [comment]
Thank you Neal for the suggestion, it took so long to implement because I did not realise it could be so easy (by redirecting back to the location)... As a bonus I've also implemented a  "Add to Read Later" flag and "Jump to location" possibility to further easy saving via the "bookmarklet"...

**Comment by adrianmatei-me** [comment]
https://www.bookmarks.dev/howto
