### ISSUE TITLE
Authentication + Authorization from Angular2 app

### ISSUE THREAD

**Issue by gldiazcardenas** [CodepediaOrg/bookmarks.dev#7]
Hi, thanks for sharing this pretty useful and detailed information, it is great to see that people share their knowledge and experience, so congrats.   I would like to ask if you have done Authentication + Authorization from the Frontend App.  I'm dealing with an issue where I can authenticate without problem from my AngularJS app, but later I need to get an Authorization token (with all permissions) the user has.  But I'm facing a CORS issue when doing the second API call to Keycloak.   I configured correctly my Web Origin (actually in dev environment I have "*" in web origin), so I can pass that authentication stage but once I arrive authorization phase I get blocked.   Do you know how to solve this problem?  Am I doing wrong trying to get authorization from Frontend app?

**Comment by adrianmatei-me** [comment]
Hey @gldiazcardenas,

This is a kind of question you ask best on stackoverflow.

Cheers,
Adrian
